---
title: "Data Simulation"
output: html_notebook
---
## Loading Libraries and Functions



```{r, setup, include=FALSE}


#workingdirectory
path_dir = "/Users/oasc/Documents/Thesis/ML_phylogeny_learning"

knitr::opts_knit$set(root.dir =path_dir)
```

```{r libraries,message=FALSE}
library(DDD)
library(MLmetrics)
library(dplyr)
library(ape)
library(diversitree)
library(RPANDA)
library(latex2exp)
library(castor)
library(phangorn)
library(svMisc)
library(torch)
library(igraph)
library(scales)
library(extraDistr)
library(emphasis)
#library(caret)



source("R/infer-general-functions.R")#Contains functions for generating the phylogenetic trees ,plotting, computing rates.
source("R/convert-phylo-to-sumstat.R")#contains the functions to compute the summary statistics of a phylogenetic tree(tips,depth)
source("R/convert-phylo-to-cblv.R") #contains the function to encode a phylogenetic tree with the "Compact Bijective Ladderized
source("R/convert-phylo-to-graph.R") #contains the function to encode a phylogenetic tree with the "Compact Bijective Ladderized
source("R/new_funcs.R")


```

```{R,Tree params}
# Set parameters DDD model simulation

n_trees   <-  10000# number of trees to generate
ss_check  <- FALSE
#set.seed(937)
set.seed(115)
```



```{R,CRBD Simulation}

 # type of the model, either: "crbd" or "bisse"
n_taxa <- c(20, 1000) # range size 


# For the CRBD model
lambda_range <- c(0.01, 1.0) # speciation rate
epsilon_range <- c(0.0, 0.9) # turnover rate
param.range.crbd <- list(
  "lambda" = lambda_range,
  "epsilon" = epsilon_range
)

### CRBD Simulation
start_time <- Sys.time()
out_crbd <- generatePhylo("crbd", n_trees, n_taxa, param.range.crbd )
end_time <- Sys.time()
print("Simulation Time for CRBD")
print(end_time - start_time)
print("=============================")

saveRDS(out_crbd$trees, paste("data_clas/phylogeny-crbd",n_trees,"ld-01-1-e-0-9.rds", sep=""))
saveRDS(out_crbd$param, paste("data_clas/true-param-crbd",n_trees,"ld-01-1-e-0-9.rds", sep=""))

```


```{R,Bisse Simulation}

 # type of the model, either: "crbd" or "bisse"
n_taxa <- c(20, 1000) # range size 

# For the BiSSE model
lambda_range <- c(0.01, 1.0) #speciation rate
q_range <- c(0.01, 0.1) # transition rate
param.range.bisse <- list(
  "lambda" = lambda_range,
  "q" = q_range
)

start_time <- Sys.time()
out_bisse <- new_generatePhyloBiSSE( n_trees, n_taxa, param.range.bisse )
end_time <- Sys.time()
print("Simulation Time for Bisse")
print(end_time - start_time)
print("=============================")

saveRDS(out_bisse$trees, paste("data_clas/phylogeny-bisse-ld-.01-1.0-q-.01-.1.rds", sep=""))
saveRDS(out_bisse$param, paste("data_clas/true-param-bisse-ld-.01-1.0-q-.01-.1.rds", sep=""))

```


```{R,DDD Simulation}
### DDD Simulation
# Set parameters DDD model simulation


#n_trees <- 100# number of trees to generate
n_trees <- 10000
lambda0_pld <- c(0, 50) # speciation rate
k_pld	<- c(20,400)         # carrying Capacity
beta_p <-c(0,0) 
crown_age_pld <- 1
start_time <- Sys.time()
output_ddd<-generatePhylo_PLD (n_trees,lambda0_pld,k_pld,beta_p,crown_age_pld,DDD=TRUE
                             ,ss_check=TRUE,max_tries =5)
end_time <- Sys.time()
print("Simulation Time for DDD")
print(end_time - start_time)
print("=============================")

phylo_name_ddd<-fname_ddd(n_trees,lambda0_pld,lambda0_pld,k_pld,crown_age_pld,10)
saveRDS(output_ddd$trees, paste("data_ddd/phylogeny-DDD2", "-",phylo_name_ddd,".rds", sep=""))
saveRDS(output_ddd$param, paste("data_ddd/true-param-DDD2", "-",phylo_name_ddd,".rds", sep=""))
saveRDS(output_ddd$brts, paste("data_ddd/brts-DDD2-",phylo_name_ddd,".rds", sep=""))

```


```{R, PLD Simulation}

source("R/new_funcs.R")
### PLD Simulation
# Set parameters DDD model simulation
## Factor for unitary trees 15


n_trees <- 10000# number of trees to generate
lambda0_pld <- c(0, 50) # speciation rate
k_pld	<- c(20,400)         # carrying Capacity
beta_p <-c(-2.5,2.5) 
crown_age_pld <- 1
#set.seed(937)
start_time <- Sys.time()
output_pld<-generatePhylo_PLD (n_trees,lambda0_pld,k_pld,beta_p,crown_age_pld,DDD=FALSE
                             ,ss_check=TRUE,max_tries =5)
end_time <- Sys.time()
print("Simulation Time for PLD")
print(end_time - start_time)
print("=============================")

phylo_name_pld<-fname_ddd(n_trees,lambda0_pld,lambda0_pld,k_pld,crown_age_pld,10)
saveRDS(output_pld$trees, paste("data_clas/phylogeny-pld", "-",phylo_name_pld,".rds", sep=""))
saveRDS(output_pld$param, paste("data_clas/true-param-pld", "-",phylo_name_pld,".rds", sep=""))
saveRDS(output_pld$brts, paste("data_clas/brts-pld-",phylo_name_pld,".rds", sep=""))


```



```{R,Histogram of Tree size Distribuition}
# Create a vector to store the phylo$Node values

node_values_crbd <- c()
node_values_bisse  <- c()
node_values_ddd <- c()
node_values_pld <- c()

# Iterate over each tree in the list
for (i in seq_along(out_crbd$trees)) {
  num_nodes <- out_crbd$trees[[i]]$Nnode  # Get the Node values for the current tree
  node_values_crbd <- c(node_values_crbd, num_nodes)  # Append the Node values to the vector
}

# Iterate over each tree in the list
for (i in seq_along(out_bisse$trees)) {
  num_nodes <- out_bisse$trees[[i]]$Nnode  # Get the Node values for the current tree
  node_values_bisse <- c(node_values_bisse, num_nodes)  # Append the Node values to the vector
}



# Iterate over each tree in the list
for (i in seq_along(output_ddd$trees)) {
  num_nodes <- output_ddd$trees[[i]]$Nnode  # Get the Node values for the current tree
  node_values_ddd <- c(node_values_ddd, num_nodes)  # Append the Node values to the vector
}



# Iterate over each tree in the list
for (i in seq_along(output_pld$trees)) {
  num_nodes <- output_pld$trees[[i]]$Nnode  # Get the Node values for the current tree
  node_values_pld <- c(node_values_pld, num_nodes)  # Append the Node values to the vector
}# Plot a histogram of node_values



hist(node_values_crbd, breaks = "FD", main = "Histogram of CRBD Node Values", xlab = "Node Values")
hist(node_values_bisse, breaks = "FD", main = "Histogram of Bisse Node Values", xlab = "Node Values")
hist(node_values_ddd, breaks = "FD", main = "Histogram of DDD Node Values", xlab = "Node Values")
hist(node_values_pld, breaks = "FD", main = "Histogram of PLD Node Values", xlab = "Node Values")



```

## Sumstat for DNN

```{R,Sumstat used DNN training}

#### Generating Summary Statistics CRBD"
print("Computing CRBD Statistics")
start_time <- Sys.time()
sumstat_bisse <- generateSumStatFromPhylo(out_crbd$trees, out_crbd$param) 
end_time <- Sys.time()
print("Finished Bisse Simulation Saving...")
print(end_time - start_time)
saveRDS(sumstat_bisse, paste("data_clas/phylogeny-bisse-",n_trees,"ld-.01-1.0-q-.01-.1-sumstat.rds",sep="")) 



#### Generating Summary Statistics Bisse"
print("Computing Bisse Statistics")
start_time <- Sys.time()
sumstat_bisse <- generateSumStatFromPhylo(out_bisse$trees, out_bisse$param) 
end_time <- Sys.time()
print("Finished Bisse  Saving...")
print(end_time - start_time)
saveRDS(sumstat_bisse, paste("data_clas/phylogeny-bisse-",n_trees,"ld-.01-1.0-q-.01-.1-sumstat.rds",sep="")) 


#### Generating Summary Statistics DDD"
print("Computing DDD Statistics")
start_time <- Sys.time()
sumstat_ddd <- generateSumStatFromPhylo(output_ddd$trees, output_ddd$param) 
end_time <- Sys.time()
print(end_time - start_time)
print("Finished DDD  Saving...")
saveRDS(sumstat_ddd, paste("data_clas/phylogeny-DDD2","-",phylo_name_ddd,"-sumstat.rds",sep="")) 


#### Generating Summary Statistics PLD"
print("Computing PLD Statistics")
start_time <- Sys.time()
sumstat_pld <- generateSumStatFromPhylo(output_pld$trees, output_pld$param) 
end_time <- Sys.time()
print(end_time - start_time)
print("Finished PLD  Saving...")
saveRDS(sumstat_pld, paste("data_clas/phylogeny-pld","-",phylo_name_pld,"-sumstat.rds",sep="")) 


```

## Encoding for CNN

```{R,MAtrix Encoding for CNN}

source("R/convert-phylo-to-cblv.R") #contains the function to encode a phylogenetic tree with the "Compact Bijective Ladderized

source("R/new_funcs.R")


phylo_crbd <- readRDS( paste("data_clas/phylogeny-crbd10000ld-01-1-e-0-9.rds", sep=""))
phylo_bisse <- readRDS( paste("data_clas/phylogeny-bisse-10000ld-.01-1.0-q-.01-.1.rds", sep=""))
phylo_ddd <- readRDS( paste("data_clas/phylogeny-DDD2-nt-10000-la0-0-50-mu-0-50-k-20-400-age-1-ddmod-10.rds", sep=""))
phylo_pld <- readRDS( paste("data_clas/phylogeny-pld-nt-10000-la0-0-50-mu-0-50-k-20-400-age-1-ddmod-10.rds", sep=""))

#phylo_crbd<-out_crbd$trees
#phylo_bisse<-out_crbd$trees
#phylo_ddd<-output_ddd$trees
#phylo_pld<-output_pld$trees


max_crbd<-getmax_nodes(phylo_crbd)
max_bisse<-getmax_nodes(phylo_bisse)
max_ddd<-getmax_nodes(phylo_ddd)
max_pld<-getmax_nodes(phylo_pld)


min_crbd<-getmin_nodes(phylo_crbd)
min_bisse<-getmin_nodes(phylo_bisse)
min_ddd<-getmin_nodes(phylo_ddd)
min_pld<-getmin_nodes(phylo_pld)

max_nodes<-max(max_ddd,max_crbd,max_bisse,max_pld)
min_nodes<- min(min_crbd,min_bisse,min_ddd,min_pld)
print("Max Nodes used for encoding save it ")
print(max_nodes)
saveRDS(max_nodes, paste("data_clas/max_nodes.rds", sep=""))
saveRDS(min_nodes, paste("data_clas/min_nodes.rds", sep=""))

start_time<- Sys.time()
cblv_crbd <- generate_encoding_DDD(phylo_crbd, tree_size = max_nodes)
cblv_bisse <- generate_encoding_DDD(phylo_bisse, tree_size = max_nodes)
cblv_ddd <- generate_encoding_DDD(phylo_ddd, tree_size = max_nodes)
cblv_pld <- generate_encoding_DDD(phylo_pld, tree_size = max_nodes)
end_time <- Sys.time()
print(end_time - start_time)

saveRDS(cblv_crbd, paste("data_clas/phylogeny-crbd10000ld-01-1-e-0-9-cblv.rds", sep=""))
saveRDS(cblv_bisse, paste("data_clas/phylogeny-bisse-10000ld-.01-1.0-q-.01-.1-cblv.rds", sep=""))
saveRDS(cblv_ddd, paste("data_clas/phylogeny-DDD2-nt-10000-la0-0-50-mu-0-50-k-20-400-age-1-ddmod-10-cblv.rds", sep=""))
saveRDS(cblv_pld, paste("data_clas/phylogeny-pld-nt-10000-la0-0-50-mu-0-50-k-20-400-age-1-ddmod-10-cblv.rds", sep=""))
#additional tree info



```


## Generate LTT  fro CNNLTT and LSTM

```{R, LTT  fo CNN+LTT and LSTM}

true_crbd   <-   list("crbd"  = rep(2, n_trees), 
                  "bisse" = rep(1, n_trees), 
                  "ddd"  = rep(1, n_trees),
                  "pld"  = rep(1, n_trees))


true_bisse   <-   list("crbd"  = rep(1, n_trees), 
                  "bisse" = rep(2, n_trees), 
                  "ddd"  = rep(1, n_trees),
                  "pld"  = rep(1, n_trees))


true_ddd   <-   list("crbd"  = rep(1, n_trees), 
                  "bisse" = rep(1, n_trees), 
                  "ddd"  = rep(2, n_trees),
                  "pld"  = rep(1, n_trees))

true_pld   <-   list("crbd"  = rep(1, n_trees), 
                  "bisse" = rep(1, n_trees), 
                  "ddd"  = rep(1, n_trees),
                  "pld"  = rep(2, n_trees))

true_names<-names(true_crbd)


true <- lapply(1:4, function(i) c(true_crbd[[i]], true_bisse[[i]], true_ddd[[i]], true_pld[[i]]))
names(true)<-true_names


saveRDS(true,  paste("data_clas/phylo-true-clas-all2.rds", sep=""))

phylo<-c(phylo_crbd,phylo_bisse,phylo_ddd,phylo_pld)

print("Generating LTT")
start_time<- Sys.time()
df.ltt_all<-generate_ltt_dataframe(phylo, max_nodes, true)$ltt
end_time <- Sys.time()
print(end_time - start_time)
print("LTT finished Saving")
saveRDS(df.ltt_all,  paste("data_clas/phylo-all-dfltt.rds", sep=""))


```


## Generate graph information for Graph Neural Network.

```{R, Generating Graph information}

####

true_crbd   <-   list("crbd"  = rep(1, n_trees), 
                  "bisse" = rep(0, n_trees), 
                  "ddd"  = rep(0, n_trees),
                  "pld"  = rep(0, n_trees))


true_bisse   <-   list("crbd"  = rep(0, n_trees), 
                  "bisse" = rep(1, n_trees), 
                  "ddd"  = rep(0, n_trees),
                  "pld"  = rep(0, n_trees))


true_ddd   <-   list("crbd"  = rep(0, n_trees), 
                  "bisse" = rep(0, n_trees), 
                  "ddd"  = rep(1, n_trees),
                  "pld"  = rep(0, n_trees))

true_pld   <-   list("crbd"  = rep(0, n_trees), 
                  "bisse" = rep(0, n_trees), 
                  "ddd"  = rep(0, n_trees),
                  "pld"  = rep(1, n_trees))

true_names<-names(true_crbd)


true <- lapply(1:4, function(i) c(true_crbd[[i]], true_bisse[[i]], true_ddd[[i]], true_pld[[i]]))
names(true)<-true_names

saveRDS(true,  paste("data_clas/phylo-true-clas-all.rds", sep=""))



#phylo<-c(phylo_crbd,phylo_bisse,phylo_ddd,phylo_pld)

print("Generating graph info")
start_time<- Sys.time()
graph_all <- generate_phylogeny_graph(phylo)
end_time <- Sys.time()

saveRDS(graph_all, paste("data_clas/phylogeny-all-graph.rds",sep=""))
print("Graph finished")

```






