---
title: "DDD  Convolutinal Neural NEtwork."
output: html_document
date: "2023-04-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{R,Libraries , messages=False}
# Importing Libraries and Sources

library(torch)
#print(getwd())
source("R/infer-general-functions.R")#Contains functions for generating the phylogenetic trees ,plotting, computing rates.
source("R/neural-network-functions.R")
source("R/convert-phylo-to-sumstat.R")#contains the functions to compute the summary statistics of a phylogenetic tree(tips,depth)
source("R/convert-phylo-to-cblv.R") #contains the function to encode a phylogenetic tree with the "Compact Bijective Ladderized
source("R/new_funcs.R")


```



```{R, Setting Enviroment}
# Set parameters DDD model simulation
set.seed(113)
device = "cpu" # change if you want to compute GPUs

n_trees <- 100000# number of trees to generate
model   <- "DDD"
lambda0 <- c(.5, 1.5) # speciation rate
mu      <- c(0.05,0.5) #  extinction rate
#k	<-c(10,20)         # carrying Capacity
k<- c(40,100)
 
crown_age <- 15 
dd_model = 1 # dd_model = 1 linear dependence in speciation rate with parameter K (= diversity where speciation = extinction)

```



``` {R,Recoverying Parameters and Statistics}


phylo_name<-fname_ddd(n_trees,lambda0,mu,k,crown_age,dd_model)
if( file.exists( paste("data/phylogeny-",model,"-",phylo_name,".rds",sep="") )==TRUE){

phylo <- readRDS( paste("data/phylogeny-",model,"-",phylo_name,".rds",sep=""))
true <- readRDS(paste("data/true-param-", model, "-",phylo_name,".rds", sep=""))

true[[3]]<-true[[3]]/100
true[[4]]<-true[[4]]/100

true<-true[c(-4)] # Removing crown age from variables


  
}else {
  
print("There is no phylogenetic tree with the  declared parameters")
}
```

```{r}
max_nodes <- 0  # Variable to store the maximum number of nodes

# Iterate over each tree in the list
for (i in seq_along(phylo)) {
  num_nodes <- phylo[[i]]$Nnode  # Get the number of nodes for the current tree
  max_nodes <- max(max_nodes, num_nodes)  # Update the maximum number of nodes if necessary
}
max_nodes_rounded <- ceiling(max_nodes / 50) * 50
```



```{R}

phylo_name<-fname_ddd(n_trees,lambda0,mu,k,crown_age,dd_model)


if( file.exists( paste("data/phylogeny-DDD","-",phylo_name,"-cblv.rds",sep=""))==FALSE){
start_time <- Sys.time()

cblv <- generate_encoding_DDD(phylo, tree_size = max_nodes_rounded)
end_time <- Sys.time()
print(end_time - start_time)

saveRDS(cblv, paste("data/phylogeny-DDD","-",phylo_name,"-cblv.rds", sep=""))
#additional tree info


}else{
  print(paste("Tree from model: ",model,", already generated. Reading file",sep=""))
  
  cblv <- readRDS( paste("data/phylogeny-DDD","-",phylo_name,"-cblv.rds",sep=""))
}
```



Define the of the training, validation and test sets.

```{R}
set.seed(113)
# Define size of datasets.
total_data_points <- n_trees
subset_size <- 10000  # Specify the size of the subset

n_train    <- floor(subset_size * .9)
n_valid    <- floor(subset_size * .05)
n_test     <- subset_size - n_train - n_valid
batch_size <- batch_size <- min(subset_size*.01, 10)

# Pick the phylogenies randomly.

ds <- convert_encode_to_dataset(cblv, true)

# Pick the random subset of data points.
subset_indices <- sample(1:ncol(cblv), subset_size)

# Split the subset into train, validation, and test indices.
train_indices <- subset_indices[1:n_train]
valid_indices <- subset_indices[(n_train + 1):(n_train + n_valid)]
test_indices  <- subset_indices[(n_train + n_valid + 1):subset_size]


#train_indices <- sample(1:ncol(cblv), n_train)
#not_train_indices <- setdiff(1:ncol(cblv), train_indices)
#valid_indices <- sample(not_train_indices, n_valid)
#test_indices  <- setdiff(not_train_indices, valid_indices)

# Create the datasets.
train_ds <- ds(cblv[1:nrow(cblv), train_indices], 
               extract_elements(true, train_indices))
valid_ds <- ds(cblv[1:nrow(cblv), valid_indices], 
               extract_elements(true, valid_indices))
test_ds  <- ds(cblv[1:nrow(cblv), test_indices], 
               extract_elements(true, test_indices))

# Create the dataloader.
train_dl <- train_ds %>% dataloader(batch_size=batch_size, shuffle=TRUE)
valid_dl <- valid_ds %>% dataloader(batch_size=batch_size, shuffle=FALSE)
test_dl  <- test_ds  %>% dataloader(batch_size=1, shuffle=FALSE)


```


```{R}
n_hidden <- 8
n_layer  <- 4
ker_size <- 10
n_input  <- nrow(cblv)
n_out    <- length(true)
p_dropout <- 0.1


# Build the CNN

cnn.net <- nn_module(
  
  "corr-cnn",
  
  initialize = function(n_input, n_out, n_hidden, n_layer, ker_size) {
    self$conv1 <- nn_conv1d(in_channels = 1, out_channels = n_hidden, kernel_size = ker_size)
    self$conv2 <- nn_conv1d(in_channels = n_hidden, out_channels = 2*n_hidden, kernel_size = ker_size)
    self$conv3 <- nn_conv1d(in_channels = 2*n_hidden, out_channels = 4*n_hidden, kernel_size = ker_size)
    self$conv4 <- nn_conv1d(in_channels = 4*n_hidden, out_channels = 8*n_hidden, kernel_size = ker_size)
    n_flatten  <- compute_dim_ouput_flatten_cnn(n_input, n_layer, ker_size)
    self$fc1   <- nn_linear(in_features = n_flatten * (8*n_hidden), out_features = 100)
    self$fc2   <- nn_linear(in_features = 100, out_features = n_out)
  },
  
  forward = function(x) {
    x %>% 
      self$conv1() %>%
      nnf_relu() %>%
      nnf_dropout(p = p_dropout) %>%
      nnf_avg_pool1d(2) %>%
      
      self$conv2() %>%
      nnf_relu() %>%
      nnf_dropout(p = p_dropout) %>%
      nnf_avg_pool1d(2) %>%
      
      self$conv3() %>%
      nnf_relu() %>%
      nnf_dropout(p = p_dropout) %>%
      nnf_avg_pool1d(2) %>%

      self$conv4() %>%
      nnf_relu() %>%
      nnf_dropout(p = p_dropout) %>%
      nnf_avg_pool1d(2) %>%
      
      torch_flatten(start_dim = 2) %>%
      self$fc1() %>%
      nnf_dropout(p = p_dropout) %>%
      nnf_relu() %>%
      
      self$fc2()
  }
)

cnn <- cnn.net(n_input, n_out, n_hidden, n_layer, ker_size) # create CNN
cnn$to(device = device) # Move it to the choosen GPU
opt <- optim_adam(params = cnn$parameters) # optimizer 
```

## Training 

```{R}
train_batch <- function(b){
  opt$zero_grad()
  output <- cnn(b$x$to(device = device))
  target <- b$y$to(device = device)
  loss <- nnf_mse_loss(output, target)
  loss$backward()
  opt$step()
  loss$item()
}

valid_batch <- function(b) {
  output <- cnn(b$x$to(device = device))
  target <- b$y$to(device = device)
  loss <- nnf_mse_loss(output, target)
  loss$item()
}
```


```{R}
# Initialize parameters for the training loop 
epoch <- 1
trigger <- 0
patience <- 10
n_epochs <- 100
last_loss <- 100


# Training loop 


train_losses <- list()
valid_losses <- list()
train_plots <- list()
valid_plots <- list()
start_time <-  Sys.time()
while (epoch < n_epochs & trigger < patience) {
  
  # Training part 
  cnn$train()
  train_loss <- c()
  
  coro::loop(for (b in train_dl) {
    loss <- train_batch(b)
    train_loss <- c(train_loss, loss)
  })
  
  cat(sprintf("epoch %0.3d/%0.3d - train - loss: %3.5f \n",
              epoch, n_epochs, mean(train_loss)))
  
  # Evaluation part 
  cnn$eval()
  valid_loss <- c()
  
  coro::loop(for (b in test_dl) {
    loss <- valid_batch(b)
    valid_loss <- c(valid_loss, loss)
  })
  
  current_loss <- mean(valid_loss)
  if (current_loss > last_loss){trigger <- trigger + 1}
  else{
    trigger   <- 0
    last_loss <- current_loss
  }
  
  cat(sprintf("epoch %0.3d/%0.3d - valid - loss: %3.5f \n", epoch, n_epochs, current_loss))
  
  train_losses <- c(train_losses, mean(train_loss))
  valid_losses <- c(valid_losses, current_loss)
  
  epoch <- epoch + 1 
}
end_time <- Sys.time()

print(end_time - start_time)

```


```{R}

# Plot the loss curve
plot(1:length(train_losses), train_losses, type = "l", col = "blue",
     xlab = "Epoch", ylab = "Loss", main = "Training and Validation Loss",
     ylim = range(c(train_losses, valid_losses)))
lines(1:length(valid_losses), valid_losses, type = "l", col = "red")
legend("topright", legend = c("Training Loss", "Validation Loss"),
       col = c("blue", "red"), lty = 1)


```


## Saving the model

```{r,Storing the Model}

torch_save(cnn, paste( "M03_CNN-DDD-K",k[1],k[2],
                       subset_size,"Lay",n_layer,"Hn",n_hidden,"ker",ker_size,"p",patience,sep="-"))
cat(paste("\n Model cnn saved", sep = ""))
cat("\nSaving model... Done.")

cnn<-torch_load( paste( "M03_CNN-DDD-K",k[1],k[2],
                        subset_size,"Lay",n_layer,"Hn",n_hidden,"ker",ker_size,"p",patience,sep="-"))

```
```{R}
cnn<-torch_load( paste( "M03_CNN-DDD-K",k[1],k[2],
                        subset_size,"Lay",n_layer,"Hn",n_hidden,"ker",ker_size,"p",patience,sep="-"))
cnn$to(device=device)

```

## Evaluation 

Compute predicted parameters on test set.

```{R}
cnn$eval()
pred <- vector(mode = "list", length = n_out)
names(pred) <- names(true)

# Compute predictions 
coro::loop(for (b in test_dl) {
  out <- cnn(b$x$to(device = device))
  p <- as.numeric(out$to(device = "cpu")) # move the tensor to CPU 
  for (i in 1:n_out){pred[[i]] <- c(pred[[i]], p[i])}
})
```

Now that you have the predicted parameters you can, for instance, 
plot the predicted value by the neural network vs. the true values.

## Plots Prediction vs Predicted
```{R, Plots Prediciton vs Predicted}
# Prepare plot 
par(mfrow = c(1, 3))

plot(true[[1]][test_indices], pred[[1]], main = "lambda0", xlab = "True", ylab = "Predicted")
abline(0, 1,col="red")

plot(true[[2]][test_indices], pred[[2]], main = "mu", xlab = "True", ylab = "Predicted")
abline(0, 1,col="red")

plot(true[[3]][test_indices] * 100, pred[[3]] * 100, main = "K", xlab = "True", ylab = "Predicted")
abline(0, 1,col="red")
```

```{R,computing RMSE}

mse_l <- list()

for (i in 1:length(true))
{
  mse<- sqrt(mean((true[[i]][test_indices]-pred[[i]])^2))/mean(true[[i]][test_indices])
  mse_l<-c(mse_l, mse)
}

names(mse_l) <- names(true)

mse_l


```


```{R,NRME against bucket, Only on testing}

phylo_name<-fname_ddd(n_trees,lambda0,mu,k,crown_age,dd_model)
phylo <- readRDS( paste("data/phylogeny-",model,"-",phylo_name,".rds",sep=""))

# Get the Nnode values for each tree
node_values <- sapply(phylo[test_indices], function(tree) tree$Nnode)

# Group the indices based on the Nnode values
grouped_indices <- split(seq_along(phylo[test_indices]), node_values)


h <- list()
for( i in 1:length(true)){
  h[[names(true[i])]] <- list()
  
  # Iterate over each group
  for (j in names(grouped_indices)) {
    tree_indices <- grouped_indices[[j]]  # Get the tree indices for the current group
    
    # Get the values for the current name and tree indices
    #values <- true[[i]][tree_indices]
    
    nrmse <- sqrt(mean((true[[i]][test_indices][tree_indices]-pred[[i]][tree_indices])^2))/mean(true[[i]][test_indices][tree_indices])
    
    # Store the values in h
    h[[i]][[j]] <- nrmse
    
    }
  
  
}

```


## Plotting Tree Size vs NRMSE 
```{R, Plotting NRMSE Tree Size }
# Scatter plot for each h[i]
for (i in 1:length(h)) {
  nrmse_values <- unlist(h[[i]])  # Get the NRMSE values for the current h[i]
  
  # Create a scatter plot
  plot(x = as.integer(names(h[[i]])),
       y = nrmse_values,
       xlab = "Number of Nodes in Tree",
       ylab = "NRMSE",
       main = paste("Scatter Plot of NRMSE -", names(h)[i]))
}


```
