---
title: "R Notebook"
output: html_notebook
---

## Loading Libraries and Functions

```{r libraries,message=FALSE}
library(DDD)
library(MLmetrics)
library(dplyr)
library(ape)
library(diversitree)
library(RPANDA)
library(latex2exp)
library(castor)
library(phangorn)
library(svMisc)
library(torch)
library(igraph)
library(scales)
library(extraDistr)
#library(caret)




source("R/infer-general-functions.R")#Contains functions for generating the phylogenetic trees ,plotting, computing rates.
source("R/convert-phylo-to-sumstat.R")#contains the functions to compute the summary statistics of a phylogenetic tree(tips,depth)
source("R/convert-phylo-to-cblv.R") #contains the function to encode a phylogenetic tree with the "Compact Bijective Ladderized
source("R/new_funcs.R")


```

```{R,Tree params}
# Set parameters DDD model simulation

n_trees <- 100000# number of trees to generate
model   <- "DDD"
lambda0 <- c(.5, 1.5) # speciation rate
mu      <- c(0.05,0.5) #  extinction rate
k	<-c(40,100)         # carrying Capacity
 
crown_age <- 15 
dd_model = 1 # dd_model = 1 linear dependence in speciation rate with parameter K (= diversity where speciation = extinction)


```


## Generating Tree
```{r, generate phylo tree}


###Check if tree exists
phylo_name<-fname_ddd(n_trees,lambda0,mu,k,crown_age,dd_model)


if( file.exists( paste("data/phylogeny-", model,"-",phylo_name,".rds",sep=""))==FALSE){
start_time <- Sys.time()

out <- generatePhyloDDD( n_trees,lambda0,mu,k ,age1 = crown_age,ddmodel1=dd_model)
end_time <- Sys.time()
print(paste("Time generating Phylogenetic Tree: ",end_time - start_time,sep="" ))

phylo <- out$trees
params <- out$param

saveRDS(phylo, paste("data/phylogeny-", model, "-",phylo_name,".rds", sep=""))
saveRDS(params, paste("data/true-param-", model, "-",phylo_name,".rds", sep=""))

#additional tree info

saveRDS(out$tas, paste("data/tas-", model, "-",phylo_name,".rds", sep=""))
saveRDS(out$L, paste("data/L-", model, "-",phylo_name,".rds", sep=""))
saveRDS(out$brts, paste("data/brts-", model, "-",phylo_name,".rds", sep=""))


}else{
  print(paste("Tree from model: ",model,", already generated",sep=""))
}
```
```{r, "Generating Summary Statistics"}
if (file.exists( paste("data/phylogeny-",model,"-",phylo_name,"-sumstat.rds",sep=""))==FALSE) {
start_time <- Sys.time()
sumstat <- generateSumStatFromPhylo(phylo, params) 
end_time <- Sys.time()
saveRDS(sumstat, paste("data/new-phylogeny-",model,"-sumstat.rds",sep="")) 
print(paste("Time generating Phylogenetic Tree: ",end_time - start_time,sep="" ))
}else
{
print(paste("Summary statistics from model: ",model," with the considered parameters already generated",sep=""))
}
```